### ISSUE TITLE
Hard coded IB particle limit

### ISSUE THREAD

**Issue by DanW97** [lethe-cfd/lethe#432] opened 2022-03-16 09:52 UTC
Hi, 

First off I'd like to say that I am amazed at just how good and easy to use this code is!

I am running simulations of fluid flowing past packed spheres in a box, using sharp particles and by default I cannot have more than 50 particles present. I found that in `parameters.cc`, on line 1836 we have:
`unsigned int max_ib_particles = 50;`

Currently, I have modified this line to a larger number and recompiled to allow the use of more particles. So, my question is - is there a need to have a hard coded limit in the source code?

**Comment by blaisb** [comment] 2022-03-16 17:15
Dear Dan,
Thank you very much for the comments! It means a lot to us (I think @Luckabarbeau  will be very happy about this).
There is no need to have such a hard coded limit in the source code. however, specifying each particle individually with subsections becomes quite inconvenient at this stage. It's a weird limitation of the current parameter file.
What @Luckabarbeau and I were thinking was to add a way to massively insert the particles from a .dat file that would would specify the information in a line / column format. However, for the time being, we'll gladly increase the default limit.

To be honest, initially we were not expecting the code to scale that well for large number of particles, but things actually work quite well for a few hundred particles.

We would be glad to hear more about what you are doing with it! So if you can tell us more, we'll be glad to read about it.

Take care
Bruno

**Comment by Luckabarbeau** [comment] 2022-03-16 17:57
Hi @DanW97,

First, huge thanks for taking the time to try our code, it means a lot to us. Has @blaisb pointed out the limits is only present to avoid instantiation of a large number of particle subsection in the parameter file. We are looking at improving the initialization of a larger number of particles by using a .dat file. In the meantime, there is no problem increasing the limits of particles to a higher number it won't impact the code negatively. 

The documentation associated with the code is still in development so don't hesitate to write to us with any questions. Also, we would be very happy to hear about what you are using the code for.

Cheers,

Lucka

**Comment by DanW97** [comment] 2022-03-25 09:13
Hi both,

I use Python to write the latter half of the .prm file in a for loop as I agree that the current approach would become tedious otherwise, and also the .prm file would end up quite long. My undergrad research project used LAMMPS and that accepted .dat files for particle positions generated programmatically (we had ca. 196k particles) which was quite convenient as you could see either the actual simulation setup, with particle insertion being just "look in this file for where they are" rather than an absurd number of lines for each position and if you wanted to check the positions you can just load in the .dat file. So the .dat file approach would be a great addition to lethe!

What I am working on is generating a lot of data for forces over packed spheres that, with a brilliant tool that @anicusan is working on, can be turned into very accurate drag laws via some crazy symbolic regression work that he's doing. The largest simulation i have running is 220 particles. I've also been creating superquadric IB particles in gmsh for this work too, where they can be (as long as gmsh allows) arbitrarily scaled and rotated. If you're interested, you can find the code here: https://github.com/uob-positron-imaging-centre/MED-meshes

Cheers,

Dan

**Comment by mostanad** [comment] 2022-05-05 02:02
Hi, Dan and Lethe developers,
First of all, I should say thanks for your nice attempt at this fantastic package.

I hope you are doing well. I am another user of Lethe, and it seems that I am looking for the same thing with a pack of particles using the sharp interface method. To be sure, are you trying to find a drag law for a system of particles using sharp-interface LBM? If so, I can notice some points regarding Lethe and what it should be.

First, Blais and Lucka. I have added the Herschel-Bulkely model to the package and I tested it for a fixed particle, which shows me a good accuracy. So I will be happy if you can add this rheology to the package along with Newtonian, Carreau, and PL.

Then, the code, based on its accuracy, has a large capacity. These are the points about a powerful CFD-DEM tool, based on experience with different packages:

1- **Periodic BC**. Here because of some unclear explanations in documentation, the periodic BC implementation is not applicable. Can we apply a periodic BC across all three directions? Not only for fluid flow, what about particles mirror if a part of a particle, even in the fixed system, is crossing the boundary? Also, what about a particle settling in an unbounded domain? You just tested the settling particle in a box. 

2- **Parallelization**. I still have a major problem with its parallelization. I can't allocate more than half of the exiting cores on my system as beyond that, it calculates drag force incorrectly. It seems that the other cores should be remained for some single-core calculations, like drag force. 

If you solve this kind of problem in Lethe, the package will be suitable for some huge simulations like developing drag force correlations. Otherwise, I don't see any suitability in Lethe for multi-particle systems, and it will be limited to benchmark cases.

I only wanted to show you your package abilities.

**Comment by mostanad** [comment] 2022-05-05 02:31
> Hi both,
> 
> I use Python to write the latter half of the .prm file in a for loop as I agree that the current approach would become tedious otherwise, and also the .prm file would end up quite long. My undergrad research project used LAMMPS and that accepted .dat files for particle positions generated programmatically (we had ca. 196k particles) which was quite convenient as you could see either the actual simulation setup, with particle insertion being just "look in this file for where they are" rather than an absurd number of lines for each position and if you wanted to check the positions you can just load in the .dat file. So the .dat file approach would be a great addition to lethe!
> 
> What I am working on is generating a lot of data for forces over packed spheres that, with a brilliant tool that @anicusan is working on, can be turned into very accurate drag laws via some crazy symbolic regression work that he's doing. The largest simulation i have running is 220 particles. I've also been creating superquadric IB particles in gmsh for this work too, where they can be (as long as gmsh allows) arbitrarily scaled and rotated. If you're interested, you can find the code here: https://github.com/uob-positron-imaging-centre/MED-meshes
> 
> Cheers,
> 
> Dan

Contact me if it is possible for you: mohammad.fazli@monash.edu
It will be good to share some details with you.

**Comment by mostanad** [comment] 2022-05-05 02:52
Dear Bruno and Lucka,
[Here](https://github.com/mostanad/Herschel-Lethe.git) you can find the modified files for the Herschel-Bulkley model. The sample of model characteristics in prm will be:

`#---------------------------------------------------
# Physical Properties
#---------------------------------------------------
subsection physical properties
    set non newtonian flow	= true
    subsection non newtonian
    	set model 		= herschel
    	subsection herschel
	    	set viscosity_0    = 10
	    	set tauy 		   = 0.04647
	    	set m 		       = 1000
	    	set k 		       = 0.02389
	    	set n 		       = 0.5
	end
    end
end`

**Comment by blaisb** [comment] 2022-05-06 13:48
> Dear Bruno and Lucka, [Here](https://github.com/mostanad/Herschel-Lethe.git) you can find the modified files for the Herschel-Bulkley model. It is based on papanastasiu regularization method. The sample of model characteristics in prm will be:
> 
> ```
> #---------------------------------------------------
> # Physical Properties
> #---------------------------------------------------
> subsection physical properties
>     set non newtonian flow	= true
>     subsection non newtonian
>     	set model 		= herschel
>     	subsection herschel
> 	    	set viscosity_0    = 10
> 	    	set tauy 		   = 0.04647
> 	    	set m 		       = 1000
> 	    	set k 		       = 0.02389
> 	    	set n 		       = 0.5
> 	end
>     end
> end
> ```

@mostanad , please feel free to make a pull request if you want to include this model into Lethe. It will be our pleasure to review it and include it.

**Comment by blaisb** [comment] 2022-05-06 14:00
Dear @mostanad 

> Hi, Dan and Lethe developers, First of all, I should say thanks for your nice attempt at this fantastic package.

Thanks. We try our best to achieve our best.

> 
> I hope you are doing well. I am another user of Lethe, and it seems that I am looking for the same thing with a pack of particles using the sharp interface method. To be sure, are you trying to find a drag law for a system of particles using sharp-interface LBM? If so, I can notice some points regarding Lethe and what it should be.
> 
> First, Blais and Lucka. I have added the Herschel-Bulkely model to the package and I tested it for a fixed particle, which shows me a good accuracy. So I will be happy if you can add this rheology to the package along with Newtonian, Carreau, and PL.

Feel free to make a PR regarding this feature. Lethe is a true open-source code. Not only people from our research group contribute to it. We have had amazing contributions from people outside the Lethe organisation in the past and this is very fun. We review PRs that come from the outside with the same degree of care and attention that we do to our own.  

> 
> Then, the code, based on its accuracy, has a large capacity. These are the points about a powerful CFD-DEM tool, based on experience with different packages:
> 
> 1- **Periodic BC**. Here because of some unclear explanations in documentation, the periodic BC implementation is not applicable. Can we apply a periodic BC across all three directions? Not only for fluid flow, what about particles mirror if a part of a particle, even in the fixed system, is crossing the boundary? Also, what about a particle settling in an unbounded domain? You just tested the settling particle in a box. In unbounded domain, the criterion should be for the mixture mean velocity (should be zero), and as I know, your code only applies the desired flow rate in the fluid cells.

We have not encountered any problems on which we actively work for which we needed this feature. It would be indeed not too much work to implement it and test it. Feel free to make a pull request for this feature and we will gladly review it.

> 
> 2- **Parallelization**. I still have a major problem with its parallelization. I can't allocate more than half of the existing cores on my system as beyond that, it calculates drag force incorrectly. It seems that the other cores should be remained for some single-core calculations, like drag force.

There seems to be an issue right now with the resolved CFD-DEM force calculation when the code is using a single thread. All of our machines at the office and on the cluster have N cores and 2N threads, so we have never encountered this issue because all of our simulations are naturally threaded. Thanks for pointing this out. @Luckabarbeau and I we will try to fix this in the coming months. It might take us a day or a month, but please understand that these type of bugs are normal in a research code.


> 
> If you solve this kind of problem in Lethe, the package will be suitable for some huge simulations like developing drag force correlations. Otherwise, I don't see any suitability in Lethe for multi-particle systems, and it will be limited to benchmark cases. I can give you more details of what I am thinking. Trust me, your package is so powerful!
> 
> I only wanted to show you your package abilities.

I am glad you do. However, please feel free to make an active contribution to it. Like I previously mentioned, this is an open-source code and everybody can chime in. I'll be super happy to review their work. If you find bugs and issues like the aforementioned ones, it is nice to report them, but trying to chime in an develop a patch for them is a significantly more productive contribution for us. This is how I started to become an active member of the deal.II community (providing patch, providing documentation, etc.). If you feel something is missing, take it without your own hands, upgrade it and write it up, and it will be our pleasure to include it.
Waiting for us to make some of the changes is not the optimal strategy. We do what we can to support, and will continue to do so.


> 
> Cheers, Mohammad

**Comment by mostanad** [comment] 2022-05-09 06:26
Thanks Bruno for your nice comments. I tried to git and compile the modified Lethe version on Github, but I found a considerable change in the solver which seems weird to me. It seems that the current version, in contrast to the previous one, is solving the domain inside the solid body. I tested both Newtonian and non-Newtonian cases on Lethe and It shows me some pressure values even in the solid cells. I hadn't seen this in the previous version, and I think it was Lethe's advantage over the other packages. To this end, I provided the figures (two different cases) that you can find through this [link.](https://www.kapwing.com/videos/6278b39126db1e0058c4f25e)

**Comment by DanW97** [comment] 2022-05-09 06:41
> I hope you are doing well. I am another user of Lethe, and it seems that I am looking for the same thing with a pack of particles using the sharp interface method. To be sure, are you trying to find a drag law for a system of particles using sharp-interface LBM? If so, I can notice some points regarding Lethe and what it should be.

Yes that's spot on. I'm currently reworking the mesh generation that I'm using to replace the sharp particles with spheres cut out of a box domain to get better performance since the sharp interface method is overkill for objects that do not move. 

If you want to talk further about this, my email is: dtw545@bham.ac.uk

**Comment by DanW97** [comment] 2022-05-09 06:44
>It seems that the current version, in contrast to the previous one, is solving the domain inside the solid body. 

Have you set `set assemble Navier-Stokes inside particles = false` ?

**Comment by mostanad** [comment] 2022-05-09 06:46
Yes. I noticed that. As I sais, the right figure is just the [cylinder](https://github.com/lethe-cfd/lethe/tree/3247af6597628845adbef05540478d3bcf8c3292/examples/resolved_cfd-dem/cylinder_with_sharp_interface) case in examples.

**Comment by mostanad** [comment] 2022-05-09 06:48
> > I hope you are doing well. I am another user of Lethe, and it seems that I am looking for the same thing with a pack of particles using the sharp interface method. To be sure, are you trying to find a drag law for a system of particles using sharp-interface LBM? If so, I can notice some points regarding Lethe and what it should be.
> 
> Yes that's spot on. I'm currently reworking the mesh generation that I'm using to replace the sharp particles with spheres cut out of a box domain to get better performance since the sharp interface method is overkill for objects that do not move.
> 
> If you want to talk further about this, my email is: [dtw545@bham.ac.uk](mailto:dtw545@bham.ac.uk)

Do you mean something like the cut-cell method to reform the cells crossing the interface? I need to talk further about your work and the type of IBM you are trying to use. Is this still in Lethe package?

**Comment by DanW97** [comment] 2022-05-09 06:51
No,  this is controlling gmsh via python to create hex meshes that consist of a rectangular domain with spheres defined as holes in the mesh. If you drop me an email I'm happy to talk further about it :)

**Comment by blaisb** [comment] 2022-05-09 11:30
> Thanks Bruno for your nice comments. I tried to git and compile the modified Lethe version on Github, but I found a considerable change in the solver which seems weird to me. It seems that the current version, in contrast to the previous one, is solving the domain inside the solid body. I tested both Newtonian and non-Newtonian cases on Lethe and It shows me some pressure values even in the solid cells. I hadn't seen this in the previous version, and I think it was Lethe's advantage over the other packages. To this end, I provided the figure (two different cases; the right figure is for cylinder with sharp interface method) that shows you the difference [link.](https://www.kapwing.com/videos/6278b39126db1e0058c4f25e)

If you use `set assemble Navier-Stokes inside particles = false`  the flow (incompressible Navier-Stokes equations) is not solved inside the particles. Instead, we solve a regularizing poisson equation for the pressure. This "pressure" inside has no effect on the solver, it is just there to improve the conditioning of the system matrix and this has very good effects for Q2. Otherwise it is just a visual change.

**Comment by mostanad** [comment] 2022-05-12 03:35
> > Thanks Bruno for your nice comments. I tried to git and compile the modified Lethe version on Github, but I found a considerable change in the solver which seems weird to me. It seems that the current version, in contrast to the previous one, is solving the domain inside the solid body. I tested both Newtonian and non-Newtonian cases on Lethe and It shows me some pressure values even in the solid cells. I hadn't seen this in the previous version, and I think it was Lethe's advantage over the other packages. To this end, I provided the figure (two different cases; the right figure is for cylinder with sharp interface method) that shows you the difference [link.](https://www.kapwing.com/videos/6278b39126db1e0058c4f25e)
> 
> If you use `set assemble Navier-Stokes inside particles = false` the flow (incompressible Navier-Stokes equations) is not solved inside the particles. Instead, we solve a regularizing poisson equation for the pressure. This "pressure" inside has no effect on the solver, it is just there to improve the conditioning of the system matrix and this has very good effects for Q2. Otherwise it is just a visual change.

Yes, you are right Bruno. But the current version test shows the inside solid region pressure is affecting the solution. I have not seen this before in the previous version. Having a solution dependent on inside the particles nodes is violating my non-Newtonian simulation case as well. I need to check whether `set assemble Navier-Stokes inside particles = false` is considered or not.
Cheers,
Mohammad

**Comment by mostanad** [comment] 2022-05-12 23:27
Hi Lucka
Yes. You are right. For a Newtonian case, it does not affect. But for a non-Newtonian case with high viscosity inside the particle, the solution inside the particle violates the pressure field. To this end, your previous version, when we didn't solve inside the particle region and actually it didn't affect the solution around the particle, was working properly. But it seems that you are solving now inside the particle in order to calculate the contact force. A new feature.

**Comment by blaisb** [comment] 2022-07-26 14:05
This has been fixed in a PR a month ago or so :).

**Closed by blaisb** 2022-07-26 14:05 UTC

**Comment by mostanad** [comment] 2022-07-27 00:04
Sorry for opening this issue once again. I just have to check something about Lethe's approach. I have seen, both in the results and your paper, that Lethe and any other ghost-cell methods leave the inside solid body region unsolved. Therefore, the pressure field was showing a dummy value inside the particle region. Indeed, you just interpolate the value on the solid body surface into the surrounding fluid nodes and give the nodes inside the solid body that dummy value.
Therefore, as Bruno mentioned, you are solving a Poisson equation inside the solid body just for a better pre-conditioning in Q2. Is this correct? If so, why I couldn't reproduce my results with the current version. What is the contribution of interior nodes?
Sorry again for reopening the issue.
Cheers,
Mohammad

**Comment by blaisb** [comment] 2022-07-27 03:58
Dear Mohammad,
Both options are supported. You can solve the Navier-Stokes equation inside the particles or you can just solve a basic Poisson equation inside for pressure. Both give the same convergence in L2 norm for the pressure, velocity and the force applied on the particles. However, they may lead to different linear systems of equations to solve at each iteration. In some cases, it is better to not solve the Navier-stokes equations (in general this is the case). In others, it could be better to solve the Navier-Stokes equations inside. As such, we allow for both behaviour right now. 

I am not sure what is the challenge you are facing, but we used this recently for very strongly shear thinning flows and we did not encounter any significant issues :)
Best
Bruno

**Comment by mostanad** [comment] 2022-07-27 06:44
Thank you Bruno for your patience in responding to my comments.
Yes. I am familiar with the options provided in the package for solving the interior domain. I have not tested the latest modified distribution on GitHub yet, but the one that I was using makes some severe problems with pressure around the solid body in shear-thinning flow even for a case with "set assemble Navier-Stokes inside particles = false". The initial version was working accurately for a shear-thinning flow as it actually leaves inside the solid region unsolved (no value for pressure). Do you include the interior nodes in the matrix system when it is set not to solve the Navier-Stokes? If so, why I was getting some disturbing pressure domain?
